- organisaatio-solr-client/src/main/java/fi/vm/sade/organisaatio/service/search/OrganisaatioSearchService.java
Korjattu tietoturvaongelma organisaatioservice-1
https://confluence.oph.ware.fi/confluence/display/TIET/Organisaatio-service
> Solr injection

- organisaatio-service/README.txt
- organisaatio-service/pom.xml
- organisaatio-service/src/main/profile/development/META-INF/persistence.xml
- organisaatio-service/src/main/profile/standalone/META-INF/persistence.xml
- organisaatio-service/src/main/resources/META-INF/spring/context/dao-context.xml
- organisaatio-service/src/main/resources/persistence.xml
- organisaatio-service/src/main/webapp/META-INF/context.xml
- organisaatio-service/src/main/webapp/WEB-INF/web.xml
- pom.xml
- servers/pom.xml
- servers/src/main/webapp/META-INF/jetty-env.xml
- src/main/resources/oph-configuration/organisaatio.properties.template
- src/main/resources/tomcat/conf/context.xml
Based on https://github.com/Opetushallitus/valintaperusteet/pull/67
> OVT-9417: Add hikaricp configuration

- organisaatio-api/src/main/java/fi/vm/sade/organisaatio/api/model/types/OrganisaatioStatus.java
- organisaatio-api/src/main/java/fi/vm/sade/organisaatio/api/search/OrganisaatioPerustieto.java
- organisaatio-api/src/main/java/fi/vm/sade/organisaatio/api/util/OrganisaatioPerustietoUtil.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/business/impl/OrganisaatioYtjServiceImpl.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/model/Organisaatio.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/resource/OrganisaatioResourceImpl.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/resource/impl/v2/OrganisaatioResourceImplV2.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/service/util/OrganisaatioUtil.java
- organisaatio-solr-client/src/main/java/fi/vm/sade/organisaatio/service/search/OrganisaatioSearchService.java
- organisaatio-solr-client/src/main/java/fi/vm/sade/organisaatio/service/search/SolrDocumentToOrganisaatioPerustietoTypeFunction.java
- servers/pom.xml
- Lisää status OrganisaatioPerustieto DTO:hin
- Salli isommat solr kyselyt
> Kjhh 1079 KO organisaatiocache

- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/business/impl/OrganisaatioBaseClient.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/business/impl/OrganisaatioKoodistoClient.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/business/impl/OrganisaatioViestintaClient.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/resource/OrganisaatioDevResource.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/service/filters/CsrfHeaderFilter.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/service/filters/CsrfServletRequestWrapper.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/service/filters/IDContextMessageHelper.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/service/filters/InputFilter.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/service/filters/OutputFilter.java
- organisaatio-service/src/main/webapp/WEB-INF/web.xml
- organisaatio-ui/src/main/webapp/js/localisation.js
Lisätietoa: https://jira.oph.ware.fi/jira/browse/SEC-6
> SEC-6: Cross-Site Request Forgery -ongelmia useassa rajapinnassa

- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/business/impl/OrganisaatioBusinessChecker.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/business/impl/OrganisaatioYtjServiceImpl.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/model/Organisaatio.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/service/converter/OrganisaatioToOrganisaatioRDTOConverter.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/service/converter/v3/OrganisaatioToOrganisaatioRDTOV3Converter.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/service/converter/v3/OrganisaatioToOrganisaatioRDTOV3ProjectionFactory.java
- organisaatio-service/src/main/resources/db/migration/V082__duplikaatit_kielet.sql
- organisaatio-service/src/test/java/fi/vm/sade/organisaatio/business/impl/OrganisaatioYtjServiceImplTest.java
> Korjaa duplikaattien kielien lisäämisen

- organisaatio-api/src/main/java/fi/vm/sade/organisaatio/api/model/types/OrganisaatioTyyppi.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/auth/OrganisaatioPermissionServiceImpl.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/service/OrganisationHierarchyValidator.java
- organisaatio-solr-client/src/main/java/fi/vm/sade/organisaatio/service/search/OrganisaatioSearchService.java
- organisaatio-ui/src/main/webapp/js/controllers/organisaatioTreeController.js
- organisaatio-ui/src/main/webapp/js/services/refreshKoodisto.js
- organisaatio-ui/src/main/webapp/js/services/refreshOrganisaatio.js
> Uusi organisaatiotyyppi: varhaiskasvatuksen järjestäjä

- organisaatio-ui/src/main/webapp/html/organisaationmuokkaus.html
> Korjaa voimassaoloajan muokkauksen disabloinnin

- organisaatio-service/pom.xml
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/service/filters/CsrfHeaderFilter.java
- organisaatio-service/src/test/java/fi/vm/sade/organisaatio/service/filters/CsrfHeaderFilterTest.java
- automated test for #19 
- refactoring of filter code
- update of dependencies (removing super old servlet version)
> SEC-6 Test for CSRF filter

- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/model/OrganisaatioMetaData.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/service/converter/v3/OrganisaatioToOrganisaatioRDTOV3ProjectionFactory.java
- pom.xml
- Don't fetch images at v3 and v4 /findbyoids.
- Lazy load images
> OY-251_poista_findbyoids_rajapinnasta_kuvat

- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/auth/OrganisaatioPermissionServiceImpl.java
> Korjaa varhaiskasvatuksen järjestäjän muokkausoikeudet

- organisaatio-ui/src/main/webapp/js/controllers/organisaatioTreeController.js
> Korjaa oppilaitostyypillä haun käyttöliittymässä

- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/auth/OrganisaatioContext.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/auth/OrganisaatioPermissionServiceImpl.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/auth/PermissionChecker.java
- organisaatio-service/src/test/java/fi/vm/sade/organisaatio/auth/OrganisaatioContextTest.java
> Korjaa ryhmien luonnin ROLE_CRUD-käyttöoikeudella

- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/auth/PermissionChecker.java
- organisaatio-service/src/test/java/fi/vm/sade/organisaatio/auth/PermissionCheckerTest.java
MonikielinenTeksti#equals poistui commitissa 7a2db02.
OH-509
> Korjaa nimen muutoksen käyttöoikeustarkistuksen

- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/business/OrganisaatioKoodisto.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/business/impl/OrganisaatioKoodistoImpl.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/business/impl/OrganisaatioValidationServiceImpl.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/dto/Koodi.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/dto/mapping/KoodiToUriVersioMapper.java
- organisaatio-service/src/test/java/fi/vm/sade/organisaatio/business/impl/OrganisaatioBusinessServiceImplTest.java
- organisaatio-service/src/test/java/fi/vm/sade/organisaatio/business/impl/OrganisaatioKoodistoMock.java
- organisaatio-service/src/test/java/fi/vm/sade/organisaatio/business/impl/OrganisaatioValidationServiceImplTest.java
> Lisää kielen validoinnin nimille ja yhteystiedoille

- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/business/impl/OrganisaatioRestToStream.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/config/HttpClientConfiguration.java
Replaced with java-utils:java-http.
KJHH-1530
> Remove generic-common:cachingrestclient usage

- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/business/impl/OrganisaatioValidationServiceImpl.java
- organisaatio-service/src/test/java/fi/vm/sade/organisaatio/business/impl/OrganisaatioValidationServiceImplTest.java
- organisaatio-ui/src/main/webapp/html/varhaiskasvatuksentoimipaikkatietojenmuokkaus.html
- organisaatio-ui/src/main/webapp/js/controllers/varhaiskasvatuksenToimipaikanTietojenMuokkausController.js
- organisaatio-ui/src/main/webapp/js/services/refreshOrganisaatio.js
- Muutetaan kielipainotus ja toiminnallinen painotus vapaaehtoisiksi
- Korjaa usean peräkkäisen tallennuksen toimimattomuus ilman sivun virkistystä
> OH-517: vaka toimipaikka pakolliset tiedot

- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/business/impl/OrganisaatioKoodistoImpl.java
> Lisää lyhyen nimen ja kuvauksen tallennuksen koodistoon

- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/resource/YTJResource.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/service/converter/OrganisaatioRDTOToOrganisaatioConverter.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/service/converter/OrganisaatioToOrganisaatioRDTOConverter.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/service/converter/util/YhteystietoConverterUtils.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/service/converter/v3/OrganisaatioToOrganisaatioRDTOV3ProjectionFactory.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/service/converter/v4/YtjDtoToOrganisaatioConverter.java
- organisaatio-service/src/main/resources/META-INF/spring/context/service-context.xml
- organisaatio-service/src/test/java/fi/vm/sade/organisaatio/resource/YTJResourceTest.java
- organisaatio-service/src/test/resources/data/root_organisaatio_data.sql
Tämän avulla vardan rekisteröinti saa ladattua organisaation tiedot organisaatiopalvelun käyttämässä formaatissa.
KJHH-1643
> Lisää rajapinnan ytj-tiedoille (v4-formaatti)

- organisaatio-ui/src/main/webapp/html/yhteystietojenmuokkaus.html
- organisaatio-ui/src/main/webapp/js/services/organisaatioModel.js
> Lisää pakollisuuden vakatoimipaikan yhteystiedoille

- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/OrganisaatioOperation.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/service/aspects/AuditLogAspect.java
- pom.xml
- src/main/resources/oph-configuration/log4j.properties.template
> Päivittää auditloggerin versioon 8.3.0

- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/business/impl/OrganisaatioYtjServiceImpl.java
- organisaatio-service/src/test/java/fi/vm/sade/organisaatio/business/impl/OrganisaatioYtjServiceImplTest.java
- organisaatio-ui/src/main/webapp/js/services/organisaatioModel.js
> Yritysmuodon tallennus ytj:stä

- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/service/oid/OrganisaatioOIDServiceImpl.java
Yöllisissä eräajoissa paukahtaa WARN, josta puuttuu stack trace, ilmeisesti juurikin tästä. Olisi kovin hyödyllinen ongelmia selvitellessä!
> Korjattu stack tracen hukkaava lokitus.

- organisaatio-ui/src/main/webapp/html/organisaationsiirto.html
- organisaatio-ui/src/main/webapp/js/controllers/organisaatioMoveController.js
- organisaatio-ui/src/main/webapp/js/controllers/organisaatioTreeController.js
- sallittu siirto myös jos organisaatio on tyyppiä Varhaiskasvatuksen toimipaikka tai Varhaiskasvatuksen järjestäjä.
- Jos liitetään varhaiskasvatuksen toimipaikka liitos sallitaan vain toiseen varhaiskasvatuksen toimipaikkaan. Varhaiskasvatuksen toimipaikka voidaan siirtää vain varhaiskasvatuksen järjestäjän alle.
- Varhaiskasvatuksen järjestäjä voidaan liittää vain toiseen Varhaiskasvatuksen järjestäjään.
> Tehty muutos organisaatioiden sulautukseen ja siirtoon liittyen:

- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/business/impl/OrganisaatioFindBusinessServiceImpl.java
Aikaisemmin kokeiltiin eri hakuja, kunnes löytyi (tai ei)
mätsi. Käytetään regexpejä tunnistamaan annettu parametri,
ja kokeillaan vain siihen sopivia hakuja.
> OH-638 findById() tunnistamaan parametrin tyyppi.

- organisaatio-service/src/main/resources/db/migration/V20210112120000000__fix_some_history_data.sql
* Kaipaisten koulu ei ole yhdistynyt Utin kouluun
> OH-659: organisaatiohistorian korjailua

- organisaatio-service/src/main/resources/db/migration/V20210113120000000__fix_history_data.sql
* Syrjäntaan koulua ei ole uudelleen nimetty
* Syrjäntaan ja Pohjoisen koulut eivät ole yhdistyneet
* Pohjoisen koulua ei ole passivoitu
> OH-660: organisaatiohistorian korjailua

- organisaatio-ui/src/main/webapp/js/services/refreshKoodisto.js
Korjaa KJHH-1918 aiheuttaman ongelman organisaation muokkaussivulla.
> OH-666 Lisätty kunnan sallitut aliorganisaatiotyypit.

- organisaatio-ui/src/main/webapp/js/init.js
* Authentication scheme requires user specific data from
kayttooikeus service which fails due to wrong redirect
unless already having active session there already.
* Ask user data twice and ditch the result for the first, it's
most likely garbage anyway.
> OH-665: Fix: Page refresh needed on first visit to app

- organisaatio-api/src/main/java/fi/vm/sade/organisaatio/api/AbstractParam.java
- organisaatio-api/src/main/java/fi/vm/sade/organisaatio/api/DateParam.java
- organisaatio-api/src/main/java/fi/vm/sade/organisaatio/resource/ApiException.java
- organisaatio-service/build.gradle
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/business/impl/OrganisaatioBusinessServiceImpl.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/resource/ErrorMessage.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/resource/OrganisaatioResourceException.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/resource/OrganisaatioResourceImpl.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/resource/YTJResource.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/resource/YhteystietojenTyyppiResource.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/resource/impl/v2/OrganisaatioResourceImplV2.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/resource/impl/v3/OrganisaatioResourceImplV3.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/resource/impl/v4/OrganisaatioResourceImplV4.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/service/converter/ConverterFactory.java
CXF:n WebApplicationException korvattu kotikutoisella
ApiExceptionilla.
> CXF-riippuvuus poistettu.

- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/resource/ResourceControllerAdvice.java
Korvaava toiminnallisuus CXF:n virheenkäsittelylle.
> OH-691 organisaatio-service virheenkasittely

- organisaatio-ui/src/main/webapp/html/index.html
- src/main/resources/oph-configuration/security-context-backend.xml.template
* Revert some stupid things
* Bypass CAS for *.js files
> OH-694: Fix UI initialization 

- .travis.yml
- organisaatio-api/src/main/java/fi/vm/sade/organisaatio/resource/OrganisaatioApi.java
- organisaatio-api/src/main/java/fi/vm/sade/organisaatio/resource/OrganisaatioResource.java
- organisaatio-api/src/main/java/fi/vm/sade/organisaatio/resource/v2/OrganisaatioResourceV2.java
- organisaatio-api/src/main/java/fi/vm/sade/organisaatio/resource/v3/OrganisaatioResourceV3.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/config/DevWebSecurityConfiguration.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/config/WebSecurityConfiguration.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/resource/KoodistoResource.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/resource/YTJResource.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/resource/impl/v2/OrganisaatioResourceImplV2.java
- organisaatio-ui/cypress/integration/organisaatio_new_from_ytj_spec.js
- organisaatio-ui/src/api/koodisto.ts
- organisaatio-ui/src/api/ytj.ts
- allow access to api endpoints
- add defaults to query parameters
> fixing_endpoints

- .travis.yml
- mock-api/src/api/oppijanumerorekisteri-service/henkilo/GET.json
- organisaatio-ui/src/OrganisaatioApp.tsx
- organisaatio-ui/src/components/Sivut/LomakeSivu/LomakeSivu.tsx
- organisaatio-ui/src/components/Sivut/TaulukkoSivu/TaulukkoSivu.tsx
- organisaatio-ui/src/components/Taulukot/OrganisaatioHakuTaulukko/OrganisaatioHakuTaulukko.tsx
- organisaatio-ui/src/contexts/contexts.ts
- organisaatio-ui/src/types/types.ts
I got a bit carried away and also implemented context for the search parameters.
> OH-777 highilight passivated organisaatio in table

- organisaatio-ui/cypress/integration/organisaatio_nimenmuutos_spec.js
- organisaatio-ui/cypress/support/commands.js
- organisaatio-ui/src/components/Modaalit/ToimipisteenNimenmuutos/NimenMuutosFields.tsx
- organisaatio-ui/src/components/Modaalit/ToimipisteenNimenmuutos/TNBody.tsx
- organisaatio-ui/src/components/Modaalit/ToimipisteenNimenmuutos/ToimipisteenNimenmuutosModaali.tsx
- organisaatio-ui/src/components/Sivut/LomakeSivu/LomakeFields/LomakeFields.tsx
- organisaatio-ui/src/components/Sivut/LomakeSivu/UusiToimija/PerustietoLomake/PerustietoLomake.tsx
- implement copying names in ui
- refctir ti remove any
> OH-749 copy names in UI

- mock-api/scripts/generateJson.sh
- mock-api/src/api/koodisto-service/rest/json/kunta/koodi/GET.json
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/business/impl/OrganisaatioKoodistoImpl.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/dto/Koodi.java
- organisaatio-ui/package-lock.json
- organisaatio-ui/package.json
- organisaatio-ui/src/ValidationSchemas/PerustietolomakeSchema.ts
- organisaatio-ui/src/api/kayttooikeus.ts
- organisaatio-ui/src/api/koodisto.ts
- organisaatio-ui/src/api/organisaatio.test.ts
- organisaatio-ui/src/contexts/KoodistoContext.ts
- organisaatio-ui/src/contexts/contexts.test.ts
- organisaatio-ui/src/tools/mappers.test.ts
- organisaatio-ui/src/types/types.ts
- implement isDisabled for koodisto-select
- update ui-components and add mock data
- update ui-components and add mock data
- also implement disabled for kunta if over voimassaolopäivä
> OH-753 disable options in select lists

- README.md
- Add non-exhaustive technology listing to README
- Log4j version upgrade (log4shell)
- Log4j version upgrade (log4shell)
- Log4j version upgrade (log4shell)
> org2 merge resolve

- organisaatio-ui/src/OrganisaatioApp.tsx
- organisaatio-ui/src/components/InitializeApp/InitializeApp.tsx
> Raamien korjausyritys

- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/resource/component/LocalDateTimeConverter.java
Slightly different approach.
Does it make sense?
🤷‍♂️
> OH-915: Refactor LocalDateTimeConverter

- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/client/viestinvalitys/ApiResponse.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/client/viestinvalitys/CasAuthenticatedServiceClient.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/client/viestinvalitys/CasClient.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/client/viestinvalitys/Lahettaja.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/client/viestinvalitys/LuoViestiSuccessResponse.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/client/viestinvalitys/Prioriteetti.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/client/viestinvalitys/SisallonTyyppi.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/client/viestinvalitys/UnexpectedResponseException.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/client/viestinvalitys/Vastaanottaja.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/client/viestinvalitys/Viesti.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/client/viestinvalitys/ViestinvalitysClient.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/client/viestinvalitys/ViestinvalitysConfig.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/email/EmailService.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/email/QueuedEmail.java
- organisaatio-service/src/main/java/fi/vm/sade/organisaatio/resource/OsoitteetResource.java
- organisaatio-service/src/main/resources/application.properties
- organisaatio-service/src/main/resources/config/hahtuva.yml
- organisaatio-service/src/main/resources/config/pallero.yml
- organisaatio-service/src/main/resources/config/sade.yml
- organisaatio-service/src/main/resources/config/untuva.yml
- organisaatio-service/src/main/resources/db/migration/V20240111000000000__email_queue_table.sql
- organisaatio-service/src/main/resources/db/migration/V20240115000000000__email_queue_table.sql
- organisaatio-service/src/test/resources/application.properties
- organisaatio-ui/src/components/Sivut/OsoitteetSivu/OsoitteetApi.ts
- organisaatio-ui/src/components/Sivut/OsoitteetSivu/OsoitteetSivu.tsx
- organisaatio-ui/src/components/Sivut/OsoitteetSivu/ViestiStatusView.tsx
- organisaatio-ui/src/components/Sivut/OsoitteetSivu/ViestiView.tsx
- OSTJ-201 Client for calling viestinvälityspalvelu
- OSTJ-201 Email handling logic for form submission
> viestinvalitys integraatio
